### ISSUE TITLE
Abbrechen-Button in Spiel "Zahlen-Raten"

### ISSUE THREAD

**Issue by Jonah-Huellbrock** [Jonah-Huellbrock/JavaScript-HTML-Spiele#2]
In vielen Web-Browsern kann der {alert} mit „Ok“ bestätigt werden und mit „Abbrechen“ abbrechen abgebrochen werden. Bei meinem Spiel „Zahlen-Raten“ funktioniert der „Abbrechen“-Button nicht und das Spiel geht einfach weiter!

**Comment by JoJo48478** [comment]
Hi

**Comment by Jonah-Huellbrock** [comment]
Kann man mir da helfen oder bin ich mit dem Problem alleine? 😅
